export const ANIMATION_TIMINGS = {
  COOLDOWN_DURATION: 5000,
  PAUSE_AFTER_GLITCH: 500,
  COLOR_RECOVERY_DURATION: 600,
  BUTTON_READY_BUFFER: 200,
  BUTTON_PRESS_DURATION: 150,
  LOGO_SPIN_DURATION: 3000,
} as const;

export const GLITCH_CONFIG = {
  CHARS: ["·", "-", "·"],
  FRAME_TIME: 60,
  WAVE_OFFSET: 5,
  DISTANCE_THRESHOLD: 3,
  RANDOM_THRESHOLD: 0.6,
} as const;

export const GAME_STATUS_CHECK_INTERVAL = 3000;
